-- emp working as sales manager
select * from JOBS; --Sales Manager
-- Inner join
select EMP.FIRST_NAME , EMP.JOB_ID
FROM EMPLOYEES EMP LEFT  JOIN JOBS ON EMP.JOB_ID = JOBS.JOB_ID WHERE JOBS.JOB_TITLE = 'Sales Manager';

-- USING SUB QUERY
SELECT EMP.FIRST_NAME , EMP.JOB_ID FROM EMPLOYEES EMP 
WHERE EMP.JOB_ID = ( SELECT JOB_ID FROM JOBS WHERE JOBS.JOB_TITLE = 'Sales Manager');

--

SELECT * FROM DEPARTMENTS;
-- dISPLAY EMP WORKING FOR ACCOUNTING DEPT
SELECT EMP.FIRST_NAME , EMP.DEPARTMENT_ID
FROM EMPLOYEES EMP WHERE EMP.DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENTS.DEPARTMENT_NAME LIKE 'Accounting') ;


SELECT EMP.FIRST_NAME , EMP.DEPARTMENT_ID,  FROM EMPLOYEES EMP WHERE EMP.DEPARTMENT_ID IN
                              (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENTS.DEPARTMENT_NAME IN ( 'Accounting' , 'Finance'));
                              

-- dISPLAY SALARY OF EMP WHERE SAL IS MORE THAN 7000
SELECT * FROM EMPLOYEES EMP WHERE EMP.SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID IN ( 108 , 109)); -- 12008 , 9000
SELECT * FROM EMPLOYEES EMP WHERE EMP.SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID IN ( 108 , 109)); -- 12008 , 9000
SELECT * FROM EMPLOYEES EMP WHERE EMP.SALARY > SOME (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID IN ( 108 , 109)); -- 12008 , 9000


-- DISPLAY EMP NAME , SALARY AND MAX SALARY PAID IN ORG
SELECT EMP.FIRST_NAME , EMP.SALARY , (SELECT  MAX(SALARY)  FROM EMPLOYEES EMP2 ) MAXSAL
FROM EMPLOYEES EMP;


-- DISPLAY EMP NAME AND ITS DEPT NBAME

SELECT EMP.FIRST_NAME , EMP.DEPARTMENT_ID, (SELECT DEPT.DEPARTMENT_NAME  FROM DEPARTMENTS DEPT WHERE 
                                              DEPT.DEPARTMENT_ID = EMP.DEPARTMENT_ID
                                                 ) AS DEPTNAME
                            FROM EMPLOYEES EMP ;
                            
-- dISPLAY EMP NAME , SALARY AND MAX SALARY FOR HIS JOB

SELECT EMP.FIRST_NAME ,EMP.JOB_ID , EMP.SALARY , ( SELECT MAX(SALARY) FROM EMPLOYEES INN WHERE EMP.JOB_ID = INN.JOB_ID )  "MAXS SAL"
FROM EMPLOYEES EMP ;



-- WITH CLAUSE
-- YOU CAN DEFINE A SUB QUERY USING A WITH CLAAUS AND USE IT IN MAIN QUERY.

-- 
WITH
DEPTAVGSAL AS (SELECT DEPARTMENT_ID DEPTID, AVG(SALARY) AVGSAL FROM EMPLOYEES  GROUP BY DEPARTMENT_ID )
SELECT EMP.FIRST_NAME , EMP.SALARY  FROM EMPLOYEES EMP WHERE EMP.SALARY > ( SELECT AVGSAL FROM DEPTAVGSAL WHERE DEPTAVGSAL.DEPTID = EMP.DEPARTMENT_ID );


WITH
JOBDET AS (SELECT JOB_ID JID, JOB_TITLE JNAME FROM JOBS ),
DEPTDET AS (SELECT DEPARTMENTS.DEPARTMENT_ID DID, DEPARTMENTS.DEPARTMENT_NAME DNAME FROM DEPARTMENTS )

SELECT EMP.FIRST_NAME , EMP.JOB_ID , Q1.JNAME JOBtITLE , Q2.DNAME 
FROM EMPLOYEES EMP INNER JOIN (SELECT * FROM JOBDET) Q1  ON EMP.JOB_ID = Q1.JID
                    LEFT JOIN (SELECT * FROM DEPTDET )Q2 ON EMP.DEPARTMENT_ID = Q2.DID;
                    






-- Diplsy jonb title and the country emp is working.
with
JOBT AS (SELECT JOB_ID , JOB_TITLE , MAX_SALARY,MIN_SALARY FROM JOBS),
CITYWORK AS (SELECT DEPARTMENTS.DEPARTMENT_ID DID , COUNTRIES.COUNTRY_NAME  CNAME  FROM DEPARTMENTS INNER JOIN LOCATIONS USING (LOCATION_ID)
                                 INNER JOIN COUNTRIES USING (COUNTRY_ID)),
EMPJOB AS (SELECT FIRST_NAME , JOB_TITLE FROM EMPLOYEES INNER JOIN JOBT USING (JOB_ID)  )


SELECT EMP.FIRST_NAME , (SELECT JOB_TITLE FROM JOBT WHERE  JOB_ID = EMP.JOB_ID ) JOBtITLE  ,
  ( SELECT CNAME FROM CITYWORK WHERE CITYWORK.DID = EMP.DEPARTMENT_ID) COUNTRY
FROM EMPLOYEES EMP ;

                            
--- nEW QUERY

with
JOBT AS (SELECT JOB_ID , JOB_TITLE , MAX_SALARY,MIN_SALARY FROM JOBS),
CITYWORK AS (SELECT DEPARTMENTS.DEPARTMENT_ID DID , COUNTRIES.COUNTRY_NAME  CNAME  FROM DEPARTMENTS INNER JOIN LOCATIONS USING (LOCATION_ID)
                                      INNER JOIN COUNTRIES USING (COUNTRY_ID)),
EMPJOB AS (SELECT FIRST_NAME , JOB_TITLE FROM EMPLOYEES INNER JOIN JOBT USING (JOB_ID)  )
SELECT * FROM EMPJOB ;













